### ISSUE TITLE
Reload schedule when a new file appears

### ISSUE THREAD

**Issue by lenaschimmel** [dystonse/dystonse-gtfs-data#24]
Currently, the monitor reads the most recent schedule upon startup and keeps using it forever. This has severely affected the monitors output, e.g. not showing any departures for Bremen Hbf after running more than two weeks without a restart.

We already have a `FileCache<Gtfs>` in our code elsewhere, but we are not using it (correctly) for the monitor.

Such a !"§$%&/( bug.

![facepalm](https://media.giphy.com/media/tZiLOffTNGoak/source.gif)

**Comment by flauschzelle** [comment]
We fixed that with [this commit](https://github.com/dystonse/dystonse-gtfs-data/commit/9c6afee0bf01cf9246a8e9b1b155ba72b4de3dba).
